version: '3.8'

services:
  location:
    image: location:latest
    container_name: location
    env_file:
      - .env
    networks:
      - internal-network

networks:
  internal-network:
    external: true
